---
title: "PlotGood"
author: "Yu-Chen Xue"
date: "2018年6月4日"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
  word_document: default
header-includes: \usepackage{ctex}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plots

## 載入資料集
```{r}
library(ggplot2)
library(readr)
KidCreative <- read_csv("D:/WORKSPACE/DATASETS/KidCreative.csv")
data.cata <- read_csv("D:/WORKSPACE/DATASETS/KidCreative.csv")
```

### Income
```{r}
data.cata$Income <- as.factor(data.cata$Income)
data.cata$Buy <- as.factor(data.cata$Buy)

ggplot(data.cata, aes(x = Income, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### Is Married
```{r}
KidCreative$`Is Married` <- as.factor(KidCreative$`Is Married`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `Is Married`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### Has College
```{r}
KidCreative$`Has College` <- as.factor(KidCreative$`Has College`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `Has College`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### Is Professional
```{r}
KidCreative$`Is Professional` <- as.factor(KidCreative$`Is Professional`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `Is Professional`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### Dual Income
```{r}
KidCreative$`Dual Income` <- as.factor(KidCreative$`Dual Income`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `Dual Income`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### Own
```{r}
KidCreative$`Own` <- as.factor(KidCreative$`Own`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `Own`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### House
```{r}
KidCreative$`House` <- as.factor(KidCreative$`House`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `House`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### White
```{r}
KidCreative$`White` <- as.factor(KidCreative$`White`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `White`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```

### Prev Child Mag
```{r}
KidCreative$`Prev Child Mag` <- as.factor(KidCreative$`Prev Child Mag`)
KidCreative$Buy <- as.factor(KidCreative$Buy)

ggplot(KidCreative, aes(x = `Prev Child Mag`, fill = Buy)) + 
geom_bar(width = 0.75, position='dodge') + 
scale_fill_manual(values = c('gray43', 'steelblue1'))
```
