---
title: "SolutionGood"
author: "Yu-Chen Xue"
date: "2018年6月4日"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
  word_document: default
header-includes: \usepackage{ctex}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 載入資料集
```{r}
library(ggplot2)
library(readr)
KidCreative <- read_csv("D:/WORKSPACE/DATASETS/KidCreative.csv")
data.cata <- read_csv("D:/WORKSPACE/DATASETS/KidCreative.csv")
```



## 採用變數Income做回歸模型
```{r}
KidCreative$Income <- as.numeric(KidCreative$Income)
model.income <- glm(Buy~ Income, KidCreative, family = "binomial")
summary(model.income)
anova(model.income)
coef(model.income)
```

## 仿照資料集的分佈，生成數列
```{r}
x.seq <- seq(0, 75000, 1000)
x.seq
```

## 借助上述數列來做預測
```{r}
pred.income <- predict(model.income, list(Income=x.seq),type="response")
pred.income
```

## 將預測結果用圖來呈現
```{r}
plot(KidCreative$Income, KidCreative$Buy, pch = 1, xlab = "Income", ylab = "Buy")
lines(x.seq, pred.income)
```

## 收入大於63000的人群比較有可能購買雜誌
```{r}
predict(model.income, list(Income=63000),type="response")
```

## Model2：採用變數Dual Income, Own做回歸模型並進行預測
```{r}
model2 <- glm(Buy~ `Dual Income`*Own , KidCreative, family = "binomial", x=TRUE)
summary(model2)
anova(model2)
coef(model2)
exp(coef(model2))
predict(model2, list( `Dual Income`=1, Own=1),type="response")
```

## Model3：採用變數Dual Income, Is Married, Is Female, Prev Child Mag做回歸模型並進行預測
```{r}
model3 <- glm(Buy~ `Dual Income`*`Is Married`*`Is Female`*`Prev Child Mag`, KidCreative, family = "binomial")
summary(model3)
anova(model3)
coef(model3)
exp(coef(model3))
predict(model3, list(`Dual Income`=1, `Is Married`=1, `Is Female`=1, `Prev Child Mag`=1),type="response")
```

## Model4：採用變數Income, Is Female, Prev Child Mag做回歸模型並進行預測
```{r}
model4 <- glm(Buy~ Income*`Is Female`*`Prev Child Mag`, KidCreative, family = "binomial")
summary(model4)
anova(model4)
coef(model4)
exp(coef(model4))
predict(model4, list(Income=63000, `Is Female`=1, `Prev Child Mag`=1),type="response")
```

## Model5：採用變數Income, Is Female, Prev Child Mag做回歸模型並進行預測
```{r}
model5 <- glm(Buy~ Income*`Prev Child Mag`, KidCreative, family = "binomial")
summary(model5)
anova(model5)
coef(model5)
exp(coef(model5))
predict(model5, list(Income=63000, `Prev Child Mag`=1),type="response")
```
