---
title: "MZins4You"
author: "Yu-Chen Xue"
date: "2018年6月3日"
header-includes:
  \usepackage{ctex}
output:
  html_document: default
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(magrittr)
library(dplyr)
```


## Read csv file
```{r}
library(readr)
KidCreative <- read_csv("D:/WORKSPACE/DATASETS/KidCreative.csv")
```

```{r}
summary(KidCreative)
```

```{r}
plot(Buy~Income, KidCreative)
```

## Solution 1
```{r}
l1 <- lm(Buy~ Income, KidCreative)
summary(l1)
anova(l1)
coef(l1)
```

## Solution 2
### Step1
```{r}
s1 <- lm(Buy~Income*`Dual Income`*`Own`*`House`*`Is Female`*`Is Married`*White*`Prev Child Mag`*`Has College`*`Is Professional`, KidCreative)
summary(s1)
anova(s1)
coef(s1)
```

### Step2
```{r}
s2 <- lm(Buy~
              Income+
              `Dual Income`+
              `Prev Child Mag`+
              White+
              Income:Own+
              Income:`Dual Income`+
              Income:`Is Professional`+
              Income:White+
              `Prev Child Mag`:White:`Is Married`+
              Income:House:`Is Professional`:`Has College`
              , KidCreative)
summary(s2)
anova(s2)
coef(s2)
```

### Step3
```{r}
l2 <- lm(Buy~
              `Dual Income`+
              White+
              Income:Own+
              Income:`Dual Income`+
              Income:White
              , KidCreative)
summary(l2)
anova(l2)
coef(l2)
```

## Solution 3
```{r}
model <- glm(Buy~
              Income*
                 `Is Married`*
              `Is Female`*
              `Has College`*
              `Is Professional`*
              `Dual Income`*
              House*
              White*
              Own*
              `Prev Child Mag`
              , KidCreative, family = "binomial")
model.sum <- summary(model)
anova(model)
coef(model)
```

```{r}
model.sum
summary(model)$coeff[-1,4] < 0.05
```

```{r}
# Income*`Is Married`*`Is Female`*`Has College`*`Is Professional`*`Dual Income`*House*White*Own*`Prev Child Mag`
predict(model, list(Income=63000, `Is Married`=1, `Is Female`=1, `Has College`=1, `Is Professional`=1, `Dual Income`=1, House=1, White=1, Own=1, `Prev Child Mag`=1),type="terms")
```

